# Generated by Django 4.1.7 on 2023-03-26 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('avg', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.category')),
            ],
        ),
    ]
