# Generated by Django 4.1.7 on 2023-03-30 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_polls'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Polls',
            new_name='Poll',
        ),
    ]
